In [4]:
import random
import numpy

m = random.randrange(2,10)
n = random.randrange(2,10)
k = random.randrange(0,m)
print("m =",m,"; n =",n,"; k =",k);
a = numpy.zeros((m,n))

for i in range(m):
    for j in range(n):
        a[i][j] = random.randrange(-5,5)
print(a)
print("Строка",k,":")
print(a[k])

m = 5 ; n = 7 ; k = 3
[[ 4.  0.  3.  0.  3.  1.  2.]
 [ 1. -1.  4.  0. -4.  4.  3.]
 [-3.  2.  4.  4.  3.  4. -2.]
 [-1. -2.  1.  0. -2.  2. -5.]
 [-4. -4. -1.  3.  0.  2. -1.]]
Строка 3 :
[-1. -2.  1.  0. -2.  2. -5.]
