In [5]:
import random
import numpy

m = random.randrange(2,10)
n = random.randrange(2,10)
d = random.randrange(-5,5)
print("m =",m,"; n =",n,"; d =",d)
a = numpy.zeros((m,n))

c = [random.randrange(1,5) for i in range(m)]
print("Набор из ",m," чисел:")
print(c)
for i in range(m):
    for j in range(n):
        a[i][j] = c[i]+d*j
print(a)

m = 5 ; n = 4 ; d = 2
Набор из  5  чисел:
[2, 4, 2, 1, 4]
[[ 2.  4.  6.  8.]
 [ 4.  6.  8. 10.]
 [ 2.  4.  6.  8.]
 [ 1.  3.  5.  7.]
 [ 4.  6.  8. 10.]]
